package pojo;
// Generated Oct 7, 2021 1:39:50 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblAdmin generated by hbm2java
 */
@ManagedBean
public class TblAdmin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     
     public void save_admin()
     {
         DAOLogin add = new DAOLogin();
         add.add_admin(this);
     }
     
     public String login_admin()
     {
         DAOLogin uDao = new DAOLogin();
         List<TblAdmin> ad = uDao.getBy(username, password);
         try {
             if(ad != null) {
             username = ad.get(0).username;
             password = ad.get(0).password;
             return "sukses";
         }
        } catch (Exception e) {
             System.out.println(e);
        }
         
        return "gagal";
     }

    public TblAdmin() {
    }

    public TblAdmin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


