package pojo;
// Generated Oct 7, 2021 9:28:35 AM by Hibernate Tools 4.3.1

import DAO.DAORegistrasi;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblRegistrasi generated by hbm2java
 */
@ManagedBean
public class TblRegistrasi  implements java.io.Serializable {


     private Integer idUser;
     private String namaLengkap;
     private String emailUser;
     private String noTelp;
     private String jenisKelamin;

     public void save_registrasi()
     {
         DAORegistrasi add = new DAORegistrasi();
         add.add_registrasi(this);
     }
     
     public String Registrasi_user()
     {
         DAO.DAORegistrasi uDao = new DAORegistrasi();
         List<TblRegistrasi> us = uDao.getBy(namaLengkap, emailUser, noTelp, jenisKelamin);
         if (us != null)
         {
             namaLengkap = us.get(0).namaLengkap;
             emailUser = us.get(0).emailUser;
             noTelp = us.get(0).noTelp;
             jenisKelamin = us.get(0).jenisKelamin;
             return "sukses";
         }
         return "gagal";
     }
     
    public TblRegistrasi() {
    }

    public TblRegistrasi(String namaLengkap, String emailUser, String noTelp, String jenisKelamin) {
       this.namaLengkap = namaLengkap;
       this.emailUser = emailUser;
       this.noTelp = noTelp;
       this.jenisKelamin = jenisKelamin;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNamaLengkap() {
        return this.namaLengkap;
    }
    
    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap = namaLengkap;
    }
    public String getEmailUser() {
        return this.emailUser;
    }
    
    public void setEmailUser(String emailUser) {
        this.emailUser = emailUser;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }




}


